import {Goal,ActivityLevel,Difficulty,calculateFitnessPlan,recommendDifficulty} from './fitness';import {prisma} from '../db';import {HttpError} from '../middleware/errors';
export interface Exercise{name:string;equipment:string;sets?:number;reps?:number;durationMin?:number}
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const schedules:Record<Goal,string[]>={weight_loss:['Rest & Stretch','Full Body','Cardio','Steady Cardio','Full Body','Cardio','Rest & Stretch'],weight_gain:['Rest & Stretch','Full Body','Rest','Full Body','Rest','Full Body','Core'],muscle_building:['Rest & Stretch','Upper Body','Lower Body','Core','Upper Body','Lower Body','Rest'],maintain:['Rest & Stretch','Full Body','Steady Cardio','Core','Full Body','Steady Cardio','Rest']};
const base=(title:string):Exercise[]=>title==='Rest & Stretch'?[{name:'Easy walk',equipment:'None',durationMin:20},{name:'Stretching',equipment:'Yoga mat',durationMin:10}]:title==='Cardio'?[{name:'Jumping jacks',equipment:'None',durationMin:5},{name:'High knees',equipment:'None',durationMin:5},{name:'Brisk walk',equipment:'None',durationMin:20}]:title==='Steady Cardio'?[{name:'Brisk walk or jog',equipment:'None',durationMin:30},{name:'Cool-down stretching',equipment:'Yoga mat',durationMin:5}]:title==='Upper Body'?[{name:'Push-ups',equipment:'None',reps:12},{name:'Dumbbell shoulder press',equipment:'Dumbbells',reps:10},{name:'Dumbbell rows',equipment:'Dumbbells',reps:12},{name:'Bicep curls',equipment:'Dumbbells',reps:12}]:title==='Lower Body'?[{name:'Squats',equipment:'None',reps:15},{name:'Lunges',equipment:'None',reps:12},{name:'Glute bridges',equipment:'Yoga mat',reps:15},{name:'Calf raises',equipment:'None',reps:20}]:title==='Core'?[{name:'Plank',equipment:'Yoga mat',durationMin:2},{name:'Crunches',equipment:'Yoga mat',reps:20},{name:'Leg raises',equipment:'Yoga mat',reps:12}]:[{name:'Push-ups',equipment:'None',reps:12},{name:'Bodyweight squats',equipment:'None',reps:15},{name:'Dumbbell rows',equipment:'Dumbbells',reps:12},{name:'Plank',equipment:'Yoga mat',durationMin:1}];
export function generateWorkoutPlan(goal:Goal,activity:ActivityLevel){const d=recommendDifficulty(activity),sets=d==='beginner'?2:d==='intermediate'?3:4;return schedules[goal].map((title,i)=>({dayOfWeek:i,day:days[i],title,difficulty:d,exercises:base(title).map(e=>e.reps?{...e,sets,difficulty:d}:({...e,durationMin:Math.max(1,Math.round((e.durationMin||1)*(d==='beginner'?.75:d==='advanced'?1.25:1))),difficulty:d}))}))}
const meals:any={breakfast:[['Oats with banana','60 g',350,12,58,8]],lunch:[['Dal rice & salad','1 bowl',500,22,82,10]],snack:[['Greek yogurt & fruit','1 serving',180,15,25,3]],dinner:[['Paneer, chapati & vegetables','1 serving',450,25,48,17]]};
export function generateDietPlan(goal:Goal,targetCalories:number){return Object.entries(meals).map(([mealType,items]:any)=>{const factor=targetCalories/1480;const out=items.map((x:any)=>({food:x[0],portion:x[1],calories:Math.round(x[2]*factor),proteinG:Math.round(x[3]*factor),carbsG:Math.round(x[4]*factor),fatG:Math.round(x[5]*factor)}));return{mealType,items:out,calories:out.reduce((a:any,b:any)=>a+b.calories,0),proteinG:out.reduce((a:any,b:any)=>a+b.proteinG,0),carbsG:out.reduce((a:any,b:any)=>a+b.carbsG,0),fatG:out.reduce((a:any,b:any)=>a+b.fatG,0)}})}
export async function generateAndSavePlan(userId:number,requestedGoal?:Goal){const p=await prisma.profile.findUnique({where:{userId}});if(!p)throw new HttpError(400,'Please save your profile first');const old=await prisma.fitnessPlan.findUnique({where:{userId}});const goal=requestedGoal||(old?.goal as Goal);if(!goal)throw new HttpError(400,'Please choose a fitness goal');const calc=calculateFitnessPlan(p as any,goal),work=generateWorkoutPlan(goal,p.activityLevel as ActivityLevel),diet=generateDietPlan(goal,calc.targetCalories);return prisma.$transaction(async tx=>{const plan=await tx.fitnessPlan.upsert({where:{userId},create:{userId,...calc},update:calc});await tx.workoutPlan.deleteMany({where:{userId}});await tx.dietPlan.deleteMany({where:{userId}});await tx.workoutPlan.createMany({data:work.map(w=>({userId,dayOfWeek:w.dayOfWeek,title:w.title,difficulty:w.difficulty,exercises:w.exercises}))});await tx.dietPlan.createMany({data:diet.map(m=>({userId,mealType:m.mealType,items:m.items,calories:m.calories,proteinG:m.proteinG,carbsG:m.carbsG,fatG:m.fatG}))});return plan})}
